name: sevaexchange
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+123

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  uuid: ^4.5.1
  app_settings: ^6.1.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.2
  badges: ^3.1.2
  currency_converter_pro: ^0.0.7
  cached_network_image: ^3.4.1
  universal_io: ^2.2.2
  camera: ^0.11.1
  cloud_firestore: ^5.6.5 
  connectivity_plus: ^6.1.3
  flutter_typeahead: ^5.2.0
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  day_night_time_picker: ^1.3.1
  device_info_plus: ^11.3.3
  emoji_picker_flutter: ^4.3.0
  file_picker: ^10.1.2
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_remote_config: ^5.4.3
  firebase_storage: ^12.4.4
  flutter_flurry_sdk: ^3.3.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.4.4
  flutter_pdfview: ^1.3.2
  google_places_autocomplete: ^0.0.4
  flutter_launcher_icons: ^0.14.3
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^19.0.0
  easy_localization: ^3.0.7+1
  flutter_phoenix: ^1.0.0
  flutter_slidable: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.32
  google_api_headers: ^4.4.3
  google_maps_flutter: ^2.12.0
  google_sign_in: ^6.3.0
  http: ^1.0.0
  image_cropper: ^9.0.0
  image: ^4.0.17
  # Bumped image_picker to a null-safe, embedding-v2 compatible release
  # to match the image_cropper plugin and avoid native runtime crashes.
  image_picker: ^0.8.7+5
  permission_handler: ^11.3.1
  intl: ^0.19.0 
  intro_slider: ^4.2.1
  logger: ^2.5.0
  modal_progress_hud_nsn: ^0.5.1
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pin_code_text_field: ^1.6.0
  progress_dialog_null_safe: ^3.0.0
  provider: ^6.1.3
  rxdart: ^0.28.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  simple_animations: ^5.1.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_rating_bar: ^4.0.1
  store_redirect: ^2.0.0
  syncfusion_flutter_pdfviewer: ^29.1.33
  timeago: ^3.1.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  doseform:
    git:
      url: http://github.com/Drabu/DoseForm.git
      path: "packages/doseform"
  geolocator: ^14.0.0
  path_drawing: ^1.0.1
  firebase_dynamic_links: ^6.1.5
  app_links: ^6.4.1
  add_2_calendar: ^3.0.1
  

dependency_overrides:
  async: 2.13.0
  fake_async: 1.3.3
  geolocator_android: 4.6.2
  leak_tracker: 10.0.9
  material_color_utilities: 0.12.0
  intl: 0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
arbify:
  url: http://localize.sevaexchange.com
  project_id: 9
  output_dir: lib/l10n

flutter_icons:
  android: true
  ios: false
  image_path: "images/sevaX.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/googlecal.png
    - lib/assets/images/outlookcal.png
    - lib/assets/images/ical.png
    - lib/assets/images/report_icon.jpeg
    - lib/assets/images/invoice_icon.jpeg
    - lib/assets/google-logo-png-open-2000.png
    - lib/assets/images/profile.png
    - lib/assets/images/seva-x-logo.png
    - lib/assets/images/close.png
    - lib/assets/images/group_icon.png
    - lib/assets/sevaX.png
    - images/seva-x-logo-white.png
    - lib/assets/images/g.png
    - lib/assets/images/approved.png
    - lib/assets/images/genericlogo.png
    - lib/assets/images/newsimage.png
    - lib/assets/images/noimagefound.png
    - lib/assets/images/add.png
    - lib/assets/images/add_.png
    - lib/assets/images/add__.png
    - lib/assets/images/apple-logo.png
    - lib/assets/images/info.png
    - lib/assets/images/help.png
    - lib/assets/images/signin_apple.png
    - lib/assets/images/pin.png
    - lib/assets/images/recycle-bin.png
    - lib/assets/images/image_02.png
    - lib/assets/images/search.png
    - lib/assets/images/csv.png
    - lib/assets/images/send.png
    - lib/assets/images/cv.png
    - lib/assets/images/apple-id-outline-yes_2x.png
    - lib/assets/images/request_offer_agreement_icon.png
    - images/
    - images/card_provider/

    #navigation bar Icons
    - images/icons/navigation_bar_icons/home_filled.png
    - images/icons/navigation_bar_icons/home_unfilled.png
    - images/icons/navigation_bar_icons/message_filled.png
    - images/icons/navigation_bar_icons/message_unfilled.png
    - images/icons/navigation_bar_icons/notifications_filled.png
    - images/icons/navigation_bar_icons/notifications_unfilled.png
    - images/icons/navigation_bar_icons/explore_filled.png
    - images/icons/navigation_bar_icons/explore_unfilled.png
    - images/icons/navigation_bar_icons/settings_filled.png
    - images/icons/navigation_bar_icons/settings_unfilled.png

    #icons
    - images/icons/create_message.png
    - images/icons/message.png
    - images/icons/remove_user.png
    - images/icons/camera.png
    - images/icons/cash_donation.png
    - images/icons/goods_donation.png
    - images/icons/verified.png
    - images/icons/recommended.png
    - images/icons/about.png
    - images/icons/projects.png
    - images/icons/members.png
    - images/icons/link.png
    - images/icons/multi_image.png

    - images/csv_example.png
    - images/icons/empty_widget.png
    # intro_screens
    - images/intro_screens/Broadcasting_feeds.png
    - images/intro_screens/Groups_and_Projects.png
    - images/intro_screens/Messaging_and_communication.png
    - images/intro_screens/Requests_and_Offers.png
    - images/intro_screens/What_is_a_timebank_and_how_can_people_find_and_join_one.png
    # amenities icons
    - images/icons/amenities_icons/amenities.png
    - images/icons/amenities_icons/air_conditioner.png
    - images/icons/amenities_icons/alarm_clock.png
    - images/icons/amenities_icons/bath_tub.png
    - images/icons/amenities_icons/closet.png
    - images/icons/amenities_icons/clothes_hanger.png
    - images/icons/amenities_icons/coffee_machine.png
    - images/icons/amenities_icons/dental_kit.png
    - images/icons/amenities_icons/iron.png
    - images/icons/amenities_icons/ironing_board.png
    - images/icons/amenities_icons/kitchen.png
    - images/icons/amenities_icons/luggage_rack.png
    - images/icons/amenities_icons/mini_fridge.png
    - images/icons/amenities_icons/parking.png
    - images/icons/amenities_icons/safe_locker.png
    - images/icons/amenities_icons/shaving_kit.png
    - images/icons/amenities_icons/swimming_pool.png
    - images/icons/amenities_icons/television.png
    - images/icons/amenities_icons/wifi.png
    - images/icons/amenities_icons/workspace.png

  fonts:
    # - family: Montserrat
    #   fonts:
    #     - asset: fonts/Montserrat-Regular.ttf
    #     - asset: fonts/Montserrat-Black.ttf
    #     - asset: fonts/Montserrat-BlackItalic.ttf
    #     - asset: fonts/Montserrat-Bold.ttf
    #     - asset: fonts/Montserrat-BoldItalic.ttf
    #     - fonts/Montserrat-ExtraBold.ttf
    #     - fonts/Montserrat-ExtraBoldItalic.ttf
    #     - fonts/Montserrat-ExtraLight.ttf
    #     - fonts/Montserrat-ExtraLightItalic.ttf
    #     - fonts/Montserrat-Italic.ttf
    #     - fonts/Montserrat-Light.ttf
    #     - fonts/Montserrat-LightItalic.ttf
    #     - fonts/Montserrat-Medium.ttf
    #     - fonts/Montserrat-SemiBold.ttf
    #     - fonts/Montserrat-SemiBoldItalic.ttf
    #     - fonts/Montserrat-Thin.ttf
    #     - fonts/Montserrat-ThinItalic.ttf
    - family: Europa
      fonts:
        - asset: fonts/EuropaBold.ttf
        - asset: fonts/EuropaBoldItalic.ttf
        - asset: fonts/EuropaLight.ttf
        - asset: fonts/EuropaLightItalic.ttf
        - asset: fonts/EuropaRegular.ttf
        - asset: fonts/EuropaRegularItalic.ttf
    - family: MavenPro
      fonts:
        - asset: fonts/MavenPro-Regular.ttf
          weight: 400
        - asset: fonts/MavenPro-Medium.ttf
          weight: 500
        - asset: fonts/MavenPro-Bold.ttf
          weight: 700
    # - family: OpenSans
    #   fonts:
    #     - asset: fonts/OpenSans-Bold.ttf
    #     - asset: fonts/OpenSans-BoldItalic.ttf
    #     - asset: fonts/OpenSans-ExtraBold.ttf
    #     - asset: fonts/OpenSans-ExtraBoldItalic.ttf
    #     - asset: fonts/OpenSans-Italic.ttf
    #     - asset: fonts/OpenSans-Light.ttf
    #     - asset: fonts/OpenSans-LightItalic.ttf
    #     - asset: fonts/OpenSans-Regular.ttf
    #     - asset: fonts/OpenSans-SemiBold.ttf
    #     - asset: fonts/OpenSans-SemiBoldItalic.ttf
